# Generated by Django 5.1.6 on 2025-02-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='gender',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
        migrations.AddField(
            model_name='faculty',
            name='phone_num',
            field=models.CharField(default='0000000000', max_length=100),
        ),
        migrations.AddField(
            model_name='faculty',
            name='subject',
            field=models.CharField(default='Xyz', max_length=100),
        ),
    ]
