# Generated by Django 5.1.6 on 2025-02-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_faculty_gender_faculty_phone_num_faculty_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='subject',
            field=models.CharField(default='Subject', max_length=100),
        ),
    ]
