# Generated by Django 5.1.6 on 2025-03-03 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0017_rename_college_name_faculty_professional_degree'),
        ('faculty', '0005_internship'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('next_round_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('interview', 'Interview Scheduled'), ('next_round', 'Next Round Scheduled'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='applied', max_length=20)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_admin.placement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_admin.student')),
            ],
        ),
    ]
