# Generated by Django 5.1.6 on 2025-03-03 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0021_student_inter_diploma_certificate_student_resume_and_more'),
        ('faculty', '0006_placementapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_admin.placement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_admin.student')),
            ],
        ),
    ]
