# Generated by Django 5.1.6 on 2025-03-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0008_internship_end_date_internship_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='shortlisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='placementapplication',
            name='round_updates',
            field=models.TextField(blank=True, null=True),
        ),
    ]
