# Generated by Django 5.1.6 on 2025-03-03 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0009_application_shortlisted_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
