# Generated by Django 5.1.6 on 2025-03-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0010_delete_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementapplication',
            name='shortlisted',
            field=models.BooleanField(default=False),
        ),
    ]
