# Generated by Django 5.1.6 on 2025-03-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0011_placementapplication_shortlisted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('interview', 'Interview Scheduled'), ('next_round', 'Next Round Scheduled'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='applied', max_length=20),
        ),
    ]
