# Generated by Django 5.1.6 on 2025-03-05 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0012_alter_placementapplication_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacultyRegistration',
        ),
    ]
