# Generated by Django 5.1.6 on 2025-03-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChattingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_mail', models.EmailField(max_length=254)),
                ('receiver_mail', models.EmailField(max_length=254)),
                ('text', models.TextField()),
                ('share_files', models.FileField(blank=True, null=True, upload_to='sharedFiles/')),
                ('sender_chat_id', models.CharField(max_length=100, null=True)),
                ('receiver_chat_id', models.CharField(max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'db_table': 'ChattingModel',
                'ordering': ['timestamp'],
            },
        ),
    ]
