# Generated by Django 5.1.6 on 2025-03-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0002_alter_chattingmodel_share_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattingmodel',
            name='share_files',
            field=models.FileField(blank=True, null=True, upload_to='sharedFiles/'),
        ),
    ]
