# Generated by Django 5.1.6 on 2025-02-28 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(default='Not Specified', max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_num', models.CharField(default='0000000000', max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
