# Generated by Django 5.1.6 on 2025-03-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch_year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
