# Generated by Django 5.1.6 on 2025-03-02 06:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_batch_year_alter_student_student_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='StudentRegistration',
        ),
    ]
