# Generated by Django 5.1.6 on 2025-03-05 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_student_studentregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentRegistration',
        ),
    ]
