# Generated by Django 5.1.6 on 2025-03-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('AI', 'Artificial Intelligence'), ('ML', 'Machine Learning'), ('MECH', 'Mechanical Engineering')], max_length=50),
        ),
    ]
