# Generated by Django 5.1.6 on 2025-03-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0003_alter_student_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.CharField(choices=[('R22', '2022'), ('R23', '2023'), ('R24', '2024'), ('R25', '2025')], max_length=50),
        ),
    ]
