# Generated by Django 5.1.6 on 2025-03-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0004_alter_student_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
