# Generated by Django 5.1.6 on 2025-03-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0005_student_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('department', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('AI', 'Artificial Intelligence'), ('ML', 'Machine Learning'), ('MECH', 'Mechanical Engineering')], max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('faculty_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
            ],
        ),
    ]
