# Generated by Django 5.1.6 on 2025-03-01 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0008_placement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
    ]
