# Generated by Django 5.1.6 on 2025-03-02 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0012_student_btech_marks_student_hostel_day_scholar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('marks', models.IntegerField()),
                ('exam_type', models.CharField(choices=[('sem', 'Semester'), ('mid', 'Mid-Term')], max_length=10)),
                ('semester', models.IntegerField()),
                ('mid_term', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_admin.student')),
            ],
        ),
    ]
