# Generated by Django 5.1.6 on 2025-03-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0014_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='event_attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='seminar_attended',
            field=models.BooleanField(default=False),
        ),
    ]
