# Generated by Django 5.1.6 on 2025-03-03 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0016_faculty_college_name_faculty_degree_marks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='college_name',
            new_name='professional_degree',
        ),
    ]
