# Generated by Django 5.1.6 on 2025-03-03 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0017_rename_college_name_faculty_professional_degree'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placement',
            old_name='close_date',
            new_name='application_deadline',
        ),
        migrations.RenameField(
            model_name='placement',
            old_name='company_name',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='placement',
            old_name='job_role',
            new_name='job_title',
        ),
    ]
