# Generated by Django 5.1.6 on 2025-03-03 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0019_remove_student_password_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='password',
        ),
    ]
