# Generated by Django 5.1.6 on 2025-03-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0020_remove_faculty_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='inter_diploma_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='student',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='student',
            name='tenth_marks_photo',
            field=models.ImageField(blank=True, null=True, upload_to='tenth_marks/'),
        ),
    ]
