# Generated by Django 5.1.6 on 2025-03-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0021_student_inter_diploma_certificate_student_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='round_updates',
            field=models.TextField(blank=True, null=True),
        ),
    ]
