# Generated by Django 5.1.6 on 2025-03-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0022_placement_round_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='facultyChatId',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='studentChatId',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
