# Generated by Django 5.1.7 on 2025-03-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0023_faculty_facultychatid_student_studentchatid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.CharField(choices=[('R21', '2021'), ('R22', '2022'), ('R23', '2023'), ('R24', '2024'), ('R25', '2025')], max_length=50),
        ),
    ]
