# Generated by Django 5.1.7 on 2025-04-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0027_remove_email_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
