# Generated by Django 5.1.7 on 2025-04-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0028_alter_faculty_experience_alter_faculty_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('AIML', 'Artificial Intelligence and Machine Learning'), ('AIDS', 'Artificial Intelligence and Data Science'), ('CIVIL', 'Civil Engineering'), ('MECH', 'Mechanical Engineering')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('AIML', 'Artificial Intelligence and Machine Learning'), ('AIDS', 'Artificial Intelligence and Data Science'), ('CIVIL', 'Civil Engineering'), ('MECH', 'Mechanical Engineering')], max_length=50),
        ),
    ]
